CREATE TABLE [dbo].[p_Article]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Title] NVARCHAR(250) NOT NULL, 
    [Text] NVARCHAR(MAX) NULL, 
    [AuthorID] NVARCHAR(128) NULL, 
    [Data] DATE NOT NULL DEFAULT CONVERT (date, GETDATE())
)
